# ==============================================================================
# PERFIL DE EMERGENCIA: MODO RECUPERACIÓN
# ==============================================================================
spring.datasource.url=jdbc:postgresql://demoserver-pgsql.postgres.database.azure.com:5432/sgtic_secundaria?sslmode=require
spring.datasource.username=psqlAuser
spring.datasource.password=p$qlAdm1n12

spring.datasource.primary.jdbc-url=jdbc:postgresql://demoserver-pgsql.postgres.database.azure.com:5432/sgtic_secundaria?sslmode=require
spring.datasource.primary.username=psqlAuser
spring.datasource.primary.password=p$qlAdm1n12

spring.jpa.hibernate.ddl-auto=none