#spring.datasource.url=jdbc:postgresql://demoserver-pgsql.postgres.database.azure.com:5432/sgtic?user=psqlAuser&password=p$qlAdm1n12&sslmode=require
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://demoserver-pgsql.postgres.database.azure.com:5432/sgtic?user=psqlAuser&password=p$qlAdm1n12&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cmuteq@gmail.com
spring.mail.password=nrbx tadf imyu ylts
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Configuracion de Azure
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=sgtic02500;AccountKey=QfiQt2Zrh6HzjfSbZ/VyGvG5gkWigOtL2X0u0CQldUD2CcKY9yI4nLwb3LHqh1bulUVOcj7ELVB3+ASt3nTf4Q==;EndpointSuffix=core.windows.net
azure.storage.container-name=archivosgtic
# Permite un tamanio maximo por archivo (ejemplo: 10MB)
spring.servlet.multipart.max-file-size=10MB
# Permite un tamano maximo por peticion total
spring.servlet.multipart.max-request-size=10MB


spring.ai.openai.api-key=xxxxxxxxxx
