# Application
spring.application.name=SGTIC
server.port=8080

# DataSource - PostgreSQL
spring.datasource.url=jdbc:postgresql://demoserver-pgsql.postgres.database.azure.com:5432/sgtic_test?sslmode=require
spring.datasource.username=psqlAuser
spring.datasource.password=p$qlAdm1n12
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC
