# ==============================================================================
# CONFIGURACIÓN DE RUTEO AUTOMÁTICO (FAILOVER)
# ==============================================================================
# Base de Datos Principal (Nota la contraseña mala para forzar el fallo)
spring.datasource.primary.jdbc-url=jdbc:postgresql://demoserver-pgsql.postgres.database.azure.com:5432/sgtic?sslmode=require
spring.datasource.primary.username=psqlAuser
spring.datasource.primary.password=p$qlAdm1n12
spring.datasource.primary.driver-class-name=org.postgresql.Driver

spring.datasource.secondary.jdbc-url=jdbc:postgresql://demoserver-pgsql.postgres.database.azure.com:5432/sgtic_secundaria?sslmode=require
spring.datasource.secondary.username=psqlAuser
spring.datasource.secondary.password=p$qlAdm1n12
spring.datasource.secondary.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================================
# CONFIGURACIÓN DE CORREOS
# ==============================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cmuteq@gmail.com
spring.mail.password=nrbx tadf imyu ylts
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==============================================================================
# CONFIGURACIÓN DE AZURE STORAGE (ARCHIVOS)
# ==============================================================================
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=sgtic02500;AccountKey=QfiQt2Zrh6HzjfSbZ/VyGvG5gkWigOtL2X0u0CQldUD2CcKY9yI4nLwb3LHqh1bulUVOcj7ELVB3+ASt3nTf4Q==;EndpointSuffix=core.windows.net
azure.storage.container-name=archivosgtic
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==============================================================================
# CONFIGURACIÓN DE RESPALDOS Y GOOGLE DRIVE
# ==============================================================================
backup.run=false
backup.runner.script-path=C:\\SGTIC\\scripts\\run-backup.bat

backup.drive.client-id=751307869846-bq3t2i4ekjen38bcgn912ah24dndobob.apps.googleusercontent.com
backup.drive.client-secret=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
backup.drive.redirect-uri=http://localhost:8080/api/admin/drive/oauth/callback
backup.drive.scope=https://www.googleapis.com/auth/drive openid email profile
backup.drive.success-redirect=http://localhost:4200/admin/backups?drive=linked
backup.drive.failure-redirect=http://localhost:4200/admin/backups?drive=error


spring.main.web-application-type=servlet
spring.jackson.deserialization.fail-on-unknown-properties=false

# ==============================================================================
# CREDENCIALES PARA RESTAURACIÓN (Usadas por pg_restore)
# ==============================================================================
backup.restore.host=demoserver-pgsql.postgres.database.azure.com
backup.restore.port=5432
backup.restore.db-name=sgtic_secundaria
backup.restore.user=psqlAuser
backup.restore.password=p$qlAdm1n12

spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.1