package com.uteq.sgtic.dtos.student.reports;

public enum StudentReportType {
    GENERAL_STATUS,
    TITULATION_OPTION,
    TOPIC_OR_PROPOSAL,
    TOPIC_CHANGE_HISTORY,
    PROPOSAL_VERSION_HISTORY,
    DIRECTOR_ASSIGNMENT,
    THESIS_PROGRESS,
    TUTORING_HISTORY,
    ADMISSION_REQUEST
}